### Test connection
GET http://localhost:3000 HTTP/1.1

### Add a new ingredient
POST http://localhost:3000/ingredient HTTP/1.1
Content-Type: application/json

{
    "name": "test ingredient 3"
}

### Get all ingredients
GET http://localhost:3000/ingredient HTTP/1.1

### Add a new dish
POST http://localhost:3000/dish HTTP/1.1
Content-Type: application/json

{
    "name": "test dish 2",
    "ingredients": ["636f4945b60689c09c2284f3", "636f46d363a8bf8f9ac204d2"]
}

### Get all dishes
GET http://localhost:3000/dish HTTP/1.1

### Get one dish by ID
GET http://localhost:3000/dish/636f4dde535a767df8941759 HTTP/1.1